@baseUrl = http://localhost:3000
# @baseUrl = https://ai-week-1.onrender.com


GET {{baseUrl}}/health

###

POST {{baseUrl}}/ask
content-type: application/json

{
    "question": "Explain the Node.js event loop in 100 words"
}

###

POST {{baseUrl}}/tickets/classify
content-type: application/json

{
    "message": "I was charged twice."
}
###
POST {{baseUrl}}/tickets/classify
content-type: application/json

{
    "message": "My subscription isn't working."
}
###
POST {{baseUrl}}/tickets/classify
content-type: application/json

{
    "message": "My payment succeeded, but now the application won't open."
}
###
POST {{baseUrl}}/tickets/classify
content-type: application/json

{
    "message": "unable to access account, not able to reset password, charged twice, abc"
}