# @baseUrl = http://localhost:3000
@baseUrl = https://ai-week-1.onrender.com


GET {{baseUrl}}/health

###

POST {{baseUrl}}/ask
content-type: application/json

{
    "question": "Explain the Node.js event loop in 100 words"
}

###